// ============================================================
// sim_tops.cpp
// Verilator C++ harness for APEX-1 TOPS measurement.
//
// Compiles against the Verilated apex1_die model.
// Runs 8 test scenarios, prints TOPS for each, and exits with
// a non-zero code if any scenario falls below its threshold.
//
// Build:
//   verilator --sv --cc --exe --build -O3 --trace \
//     -top apex1_die \
//     -I../rtl/pkg \
//     ../rtl/pkg/apex1_pkg.sv  [all RTL sources] \
//     sim_tops.cpp
//
// Run:
//   ./obj_dir/Vapex1_die
// ============================================================

#include "Vapex1_die.h"         // Generated by Verilator
#include "verilated.h"
#include "verilated_vcd_c.h"    // Optional: waveform tracing

#include <cstdint>
#include <cstdio>
#include <cmath>
#include <string>
#include <vector>
#include <cassert>

// ── Simulation context ──────────────────────────────────
static VerilatedContext* ctx_p  = nullptr;
static Vapex1_die*       dut_p  = nullptr;
static VerilatedVcdC*    vcd_p  = nullptr;

static uint64_t sim_time = 0;   // Current simulation time (ps)
static uint64_t clk_half = 500; // Half-period in ps (500ps = 1 GHz)

// ── Clock helpers ───────────────────────────────────────
void tick() {
    // Rising edge
    dut_p->clk = 1;
    dut_p->eval();
    if (vcd_p) vcd_p->dump(sim_time);
    sim_time += clk_half;

    // Falling edge
    dut_p->clk = 0;
    dut_p->eval();
    if (vcd_p) vcd_p->dump(sim_time);
    sim_time += clk_half;
}

void ticks(int n) {
    for (int i = 0; i < n; i++) tick();
}

void reset() {
    dut_p->rst_n = 0;
    // Pull all inputs to known state
    dut_p->pcie_rx_tvalid   = 0;
    dut_p->pcie_rx_tdata[0] = 0;
    dut_p->pcie_tx_tready   = 1;
    dut_p->hbm_rd_ready     = 1;
    dut_p->hbm_wr_ready     = 1;
    dut_p->ucie_tx_ready    = 1;
    dut_p->ucie_rx_valid    = 0;
    ticks(20);
    dut_p->rst_n = 1;
    ticks(10);
}

// ── TOPS measurement state ──────────────────────────────
struct TopsResult {
    std::string name;
    double      tops;
    double      util_pct;
    uint64_t    total_ops;
    uint64_t    total_cycles;
};

// ── Performance counter ──────────────────────────────────
// We can't use the SV perf_monitor inside Verilator directly
// (Verilator doesn't support all SV-specific constructs like
// covergroups in C++ context). Instead we implement the same
// logic here in C++.

struct PerfMonitor {
    uint64_t window_start_cycle = 0;
    uint64_t ops_accumulated    = 0;
    bool     running            = false;

    static constexpr int    ARRAYS   = 8;     // 4 clusters × 2 arrays (sim: ARRAYS_PER_CLUSTER=2)
    static constexpr int    ROWS     = 128;
    static constexpr int    COLS     = 128;
    static constexpr double CLK_GHZ  = 1.0;
    static constexpr long   MACS_PEAK = (long)ARRAYS * ROWS * COLS;

    uint64_t active_mac_cycles = 0; // sum of active MACs each cycle

    void start(uint64_t cycle) {
        window_start_cycle  = cycle;
        ops_accumulated     = 0;
        active_mac_cycles   = 0;
        running             = true;
    }

    void record_tile(int m, int n, int k, bool sparse) {
        if (!running) return;
        long effective_k = sparse ? k / 2 : k;
        ops_accumulated += 2ULL * m * n * effective_k;
    }

    // Call every cycle while running, with current active-array count
    void tick_active(int n_active_arrays) {
        if (!running) return;
        active_mac_cycles += (uint64_t)n_active_arrays * ROWS * COLS;
    }

    TopsResult stop(const std::string& name, uint64_t cycle) {
        running = false;
        uint64_t elapsed = cycle - window_start_cycle;
        double tops = 0.0, util = 0.0;

        if (elapsed > 0) {
            // TOPS = ops × CLK_GHZ / cycles / 1e12
            tops = (double)ops_accumulated * CLK_GHZ / (double)elapsed / 1.0e12;
            // Utilization = active_mac_cycles / (elapsed × MACS_PEAK)
            util = (double)active_mac_cycles /
                   ((double)elapsed * (double)MACS_PEAK) * 100.0;
        }

        TopsResult r;
        r.name          = name;
        r.tops          = tops;
        r.util_pct      = util;
        r.total_ops     = ops_accumulated;
        r.total_cycles  = elapsed;
        return r;
    }
};

static PerfMonitor mon;

// ── Global cycle counter ─────────────────────────────────
static uint64_t cycle_count = 0;

void tick_and_count() {
    // Sample DUT signals before rising edge
    // (Verilator: signals are stable after eval on previous falling edge)
    int active = dut_p->executing ? PerfMonitor::ARRAYS : 0;
    mon.tick_active(active);
    tick();
    cycle_count++;
}

void ticks_counted(int n) {
    for (int i = 0; i < n; i++) tick_and_count();
}

// ── Systolic array direct driver ─────────────────────────
// For raw throughput tests we drive the systolic_array submodule
// directly through the DUT's flattened port hierarchy.
// Verilator exposes all signals as public members when built with
// --public or --public-flat-rw.
//
// Since apex1_die is the top, we can't access sub-signals directly
// without --public. Instead we use the PCIe interface to load
// instructions, or we test the systolic_array module separately.

// ── Separate systolic_array harness ──────────────────────
// For raw TOPS we build a second binary that verilates just
// systolic_array. See sim_array_tops.cpp below.
// This harness tests the full die via the PCIe interface.

// ── PCIe MWr helper ──────────────────────────────────────
void pcie_mwr(uint64_t addr, const uint64_t* data_words, int nwords) {
    // Build a simplified TLP header in pcie_rx_tdata
    // pcie_rx_tdata is a 256-bit signal: Verilator exposes as
    // an array of uint32_t (8 words) or as a VlWide<8> type.
    dut_p->pcie_rx_tvalid   = 1;
    dut_p->pcie_rx_tuser    = 0x40;  // MWr TLP type

    // Clear tdata
    for (int i = 0; i < 8; i++) dut_p->pcie_rx_tdata[i] = 0;

    // Pack TLP header (simplified):
    // [9:0]   = length in DWORDs
    // [47:40] = tag
    // [95:64] = addr_hi
    // [127:96]= addr_lo
    dut_p->pcie_rx_tdata[0] = (uint32_t)(nwords & 0x3FF);  // length
    dut_p->pcie_rx_tdata[2] = (uint32_t)(addr >> 32);       // addr_hi
    dut_p->pcie_rx_tdata[3] = (uint32_t)(addr & 0xFFFFFFFF);// addr_lo
    // Payload starts at bit 128 (word index 4)
    for (int i = 0; i < nwords && i < 4; i++)
        dut_p->pcie_rx_tdata[4 + i] = (uint32_t)(data_words[i]);

    tick_and_count();
    dut_p->pcie_rx_tvalid = 0;
    tick_and_count();
}

// Write a 128-bit instruction to instruction buffer at given slot
void write_instr(int slot,
                 uint8_t  opcode,
                 uint32_t addr_a, uint32_t addr_b, uint32_t addr_c,
                 uint16_t m, uint16_t n, uint16_t k,
                 uint8_t  dtype)
{
    // Pack instruction: [7:0]=opcode [31:8]=addr_a [55:32]=addr_b
    //                   [79:56]=addr_c [95:80]=n [111:96]=m [123:112]=k [126:124]=dtype
    uint64_t lo = ((uint64_t)opcode)
                | ((uint64_t)(addr_a & 0xFFFFFF) << 8)
                | ((uint64_t)(addr_b & 0xFFFFFF) << 32)
                | ((uint64_t)(addr_c & 0x00FFFF) << 56);
    uint64_t hi = ((uint64_t)(addr_c >> 16) & 0xFF)
                | ((uint64_t)n  << 16)
                | ((uint64_t)m  << 32)
                | ((uint64_t)(k & 0xFFF) << 48)
                | ((uint64_t)(dtype & 0x7) << 60);

    uint64_t payload[2] = { lo, hi };
    uint64_t ibuf_addr = 0x00010000ULL + (uint64_t)slot * 16;
    pcie_mwr(ibuf_addr, payload, 4);
}

// Write to a 32-bit BAR0 control register
void write_creg(uint32_t offset, uint32_t value) {
    uint64_t payload[4] = { (uint64_t)value, 0, 0, 0 };
    pcie_mwr((uint64_t)offset, payload, 1);
}

// ── Wait for seq_done with timeout ───────────────────────
bool wait_done(int max_cycles) {
    for (int i = 0; i < max_cycles; i++) {
        tick_and_count();
        if (dut_p->seq_done) return true;
    }
    fprintf(stderr, "[WARN] seq_done not seen within %d cycles\n", max_cycles);
    return false;
}

// ── Build and run a MATMUL program ───────────────────────
TopsResult run_matmul_program(const std::string& name,
                               int    n_tiles,
                               uint8_t dtype,   // 0=INT8, 2=BF16, 3=FP8
                               bool   sparse)
{
    printf("\n[TEST] %s  tiles=%d  dtype=%d  sparse=%d\n",
           name.c_str(), n_tiles, dtype, (int)sparse);

    int slot = 0;
    uint8_t matmul_op = sparse ? 0x05 : 0x03;  // SPARSE_MM or MATMUL

    for (int t = 0; t < n_tiles && slot < 4090; t++) {
        uint32_t a_addr = 0x000000 + t * 0x004000;
        uint32_t b_addr = 0x400000 + t * 0x004000;
        uint32_t c_addr = 0x800000 + t * 0x004000;

        // LOAD_TILE A
        write_instr(slot++, 0x01, a_addr, 0, a_addr, 128, 128, 128, dtype);
        // LOAD_TILE B
        write_instr(slot++, 0x01, b_addr, 0, b_addr, 128, 128, 128, dtype);
        // MATMUL (or SPARSE_MM)
        write_instr(slot++, matmul_op, a_addr, b_addr, c_addr, 128, 128, 128, dtype);
        // ACTIVATE (GELU)
        write_instr(slot++, 0x08, c_addr, 0x001, c_addr, 16384, 0, 0, dtype);
    }
    // NOP terminator
    write_instr(slot++, 0x00, 0, 0, 0, 0, 0, 0, 0);

    // Write instruction count
    write_creg(0x04, (uint32_t)slot);
    ticks_counted(4);

    // Warmup pass (not measured)
    write_creg(0x00, 1);
    wait_done(50000);
    ticks_counted(50);

    // ── Measured pass ────────────────────────────────────
    mon.start(cycle_count);

    write_creg(0x00, 1);  // exec_start
    ticks_counted(4);

    bool completed = wait_done(200000);
    if (!completed)
        fprintf(stderr, "[WARN] %s: program did not complete\n", name.c_str());

    // Manually account for tile ops (full chip: 4 clusters × tiles each)
    for (int t = 0; t < n_tiles; t++)
        mon.record_tile(128, 128, 128, sparse);

    TopsResult r = mon.stop(name, cycle_count);

    printf("[RESULT] %-30s  TOPS=%.4f  util=%.1f%%  cycles=%lu\n",
           name.c_str(), r.tops, r.util_pct, r.total_cycles);

    return r;
}

// ── Sustained TOPS: adds stall between tiles ─────────────
TopsResult run_sustained(const std::string& name, int stall_cycles) {
    printf("\n[SUSTAINED] %s  stall=%d cycles/tile\n",
           name.c_str(), stall_cycles);

    int slot = 0;
    for (int t = 0; t < 50 && slot < 4090; t++) {
        uint32_t a = 0x000000 + t * 0x4000;
        uint32_t b = 0x400000 + t * 0x4000;
        uint32_t c = 0x800000 + t * 0x4000;
        write_instr(slot++, 0x01, a, 0, a, 128, 128, 128, 0);
        write_instr(slot++, 0x03, a, b, c, 128, 128, 128, 0);
        // Insert NOPs to simulate HBM stall
        for (int s = 0; s < stall_cycles / 10 && slot < 4090; s++)
            write_instr(slot++, 0x00, 0, 0, 0, 0, 0, 0, 0);
    }
    write_instr(slot++, 0x00, 0, 0, 0, 0, 0, 0, 0);

    write_creg(0x04, (uint32_t)slot);
    ticks_counted(4);

    mon.start(cycle_count);
    write_creg(0x00, 1);
    ticks_counted(4);

    wait_done(500000);

    for (int t = 0; t < 50; t++)
        mon.record_tile(128, 128, 128, false);

    TopsResult r = mon.stop(name, cycle_count);
    printf("[RESULT] %-30s  TOPS=%.4f  util=%.1f%%\n",
           name.c_str(), r.tops, r.util_pct);
    return r;
}

// ── Main ─────────────────────────────────────────────────
int main(int argc, char** argv) {
    ctx_p = new VerilatedContext;
    ctx_p->commandArgs(argc, argv);

    dut_p = new Vapex1_die{ctx_p};

    // Optional: enable VCD tracing
    bool trace = false;
    for (int i = 1; i < argc; i++)
        if (std::string(argv[i]) == "--trace") trace = true;

    if (trace) {
        ctx_p->traceEverOn(true);
        vcd_p = new VerilatedVcdC;
        dut_p->trace(vcd_p, 99);
        vcd_p->open("apex1_tops.vcd");
        printf("[INFO] Tracing to apex1_tops.vcd\n");
    }

    // ── Initialize ────────────────────────────────────────
    dut_p->clk   = 0;
    dut_p->rst_n = 0;
    dut_p->eval();
    reset();

    printf("\n========================================\n");
    printf("  APEX-1 Verilator TOPS Measurement\n");
    printf("  [SIM MODE: 8x8 arrays, extrapolate x512 for silicon]\n");
    printf("  Clock: 1.0 GHz\n");
    printf("  Sim peak  (8 arrays/die):  %.6f TOPS\n",
           2.0 * 8 * 8 * 8 * 1.0 / 1.0e3);
    printf("  Silicon peak (128x128x16): %.3f TOPS (extrapolated)\n",
           2.0 * 16 * 128 * 128 * 1.0 / 1.0e3);
    printf("  Silicon pkg  (128x128x64): %.3f TOPS (extrapolated)\n",
           2.0 * 64 * 128 * 128 * 1.0 / 1.0e3);
    printf("========================================\n");

    std::vector<TopsResult> results;
    int failures = 0;

    // ── Test 1–4: Peak TOPS per format ───────────────────
    results.push_back(run_matmul_program("Peak_INT8_dense",   40, 0, false));
    results.push_back(run_matmul_program("Peak_BF16_dense",   40, 2, false));
    results.push_back(run_matmul_program("Peak_FP8_E4M3",     40, 3, false));
    results.push_back(run_matmul_program("Peak_INT8_sparse",  40, 0, true));

    // ── Test 5–7: Sustained TOPS under HBM pressure ──────
    results.push_back(run_sustained("Sustained_no_stall",    0));
    results.push_back(run_sustained("Sustained_10cy_stall",  10));
    results.push_back(run_sustained("Sustained_120cy_stall", 120));

    // ── Summary ───────────────────────────────────────────
    printf("\n========================================\n");
    printf("  TOPS Summary\n");
    printf("========================================\n");
    printf("  %-30s  %8s  %8s  %s\n", "Test", "TOPS", "Util%", "Status");
    printf("  %-30s  %8s  %8s  %s\n",
           "------------------------------", "--------", "--------", "------");

    // Minimum thresholds per test (per-die, not per-array)
    // These scale with implementation quality; adjust after first run.
    struct Threshold { std::string prefix; double min_tops; };
    std::vector<Threshold> thresholds = {
        {"Peak_INT8_dense",   0.005},
        {"Peak_BF16_dense",   0.001},
        {"Peak_FP8",          0.005},
        {"Peak_INT8_sparse",  0.008},
        {"Sustained_no",      0.004},
        {"Sustained_10",      0.003},
        {"Sustained_120",     0.001},
    };

    for (const auto& r : results) {
        double min_tops = 0.0;
        for (const auto& t : thresholds)
            if (r.name.find(t.prefix) == 0) { min_tops = t.min_tops; break; }

        bool pass = (r.tops >= min_tops);
        if (!pass) failures++;

        printf("  %-30s  %8.4f  %7.1f%%  %s\n",
               r.name.c_str(), r.tops, r.util_pct,
               pass ? "PASS" : "FAIL");
    }

    printf("========================================\n");

    // Extrapolate to full silicon package
    // Sim uses 8x8 arrays; silicon uses 128x128 → scale by (128/8)² = 256
    // Sim uses 2 arrays/cluster; silicon uses 4 → scale by 2
    // Total scale factor: 256 × 2 = 512
    constexpr double SIM_TO_SILICON = 512.0;
    double best_tops = 0.0;
    for (const auto& r : results)
        if (r.name.find("Peak_INT8_dense") == 0 && r.tops > best_tops)
            best_tops = r.tops;

    printf("\n  ── Sim results (8x8 arrays) ──────────────────\n");
    printf("  Sim single-die INT8:   %.6f TOPS\n", best_tops);
    printf("  Sim 4-die:             %.6f TOPS\n", best_tops * 4.0);
    printf("\n  ── Extrapolated silicon (128x128 arrays) ─────\n");
    printf("  Silicon single-die:    %.2f TOPS  (sim × %.0f)\n",
           best_tops * SIM_TO_SILICON, SIM_TO_SILICON);
    printf("  Silicon 4-die package: %.2f TOPS\n",
           best_tops * SIM_TO_SILICON * 4.0);
    printf("  Silicon sparse (2:4):  %.2f TOPS\n",
           best_tops * SIM_TO_SILICON * 4.0 * 2.0);
    printf("\n  %s  (%d failures)\n",
           failures == 0 ? "ALL TESTS PASSED" : "SOME TESTS FAILED",
           failures);

    if (trace) {
        vcd_p->close();
        delete vcd_p;
    }
    dut_p->final();
    delete dut_p;
    delete ctx_p;

    return failures;
}
